@startuml
class picture_edit_vol {
- Button btnSelect
- ImageView imageView
- Uri filePath
- int PICK_IMAGE_REQUEST
~ FirebaseStorage storage
~ StorageReference storageReference
~ String user_id
# void onCreate(Bundle)
- void SelectImage()
# void onActivityResult(int,int,Intent)
- void uploadImage()
}
class Assoc_user {
- String phone_num
- Address address
- String name
- String Email
- String about
+ ArrayList<String> posts
+ ArrayList<String> massages_req
+ <<Create>> Assoc_user(String,Address,String,String,String)
+ <<Create>> Assoc_user()
+ String getPhone_num()
+ void setPhone_num(String)
+ Address getAddress()
+ void setAddress(Address)
+ String getName()
+ ArrayList<String> getMassages_req()
+ String getAbout()
+ ArrayList<String> getPosts()
+ void setAbout(String)
+ void setName(String)
+ String getEmail()
+ void setEmail(String)
}
class EditVolunteer {
- Button add_changes
- EditText FirstNameInsert
- EditText LastNameInsert
- EditText PhoneNumberInsert
- EditText EmailInsert
- EditText addresscityinsert
- EditText addressstreetinsert
- EditText addressnuminsert
- DatabaseReference mDatabase
- TextView mDisplayDate
- DatePickerDialog.OnDateSetListener mDateSetListener
~ String user_id
~ Vol_user cure_user
~ String BirthDay
# void onCreate(Bundle)
- void update_data(String,String,String,String,int,String,String)
}
class VolunteerPage {
- Button edit
- Button logOut
- Button edit_pic
- Button SerchPost
- Button inboxResponse
- TextView FirstNameInsert
- TextView LastNameInsert
- TextView PhoneNumberInsert
- TextView EmailInsert
- ImageView profile_pic
- DatabaseReference mDatabase
- StorageReference mystorge
~ String user_id
# void onCreate(Bundle)
}
class Vol_user {
- String first_name
- String last_name
- Address address
- String phone_num
- String birth_date
- String Email
+ ArrayList<String> massages_res
+ <<Create>> Vol_user(String,String,Address,String,String,String)
+ <<Create>> Vol_user()
+ ArrayList<String> getMassages_res()
+ String getFirst_name()
+ void setFirst_name(String)
+ String getLast_name()
+ void setLast_name(String)
+ Address getAddress()
+ String getBirth_date()
+ void setBirth_date(String)
+ String getEmail()
+ void setEmail(String)
+ void setAddress(Address)
+ String getPhone_num()
+ void setPhone_num(String)
}
class responseShape {
# void onCreate(Bundle)
}
class DetailsPostGuest {
- TextView PostName
- Button back
- ImageView post_pic
- DatabaseReference mDatabase
- StorageReference mystorge
~ String post_id
# void onCreate(Bundle)
}
interface Volunteer_user {
+ String getFirst_name()
+ void setFirst_name(String)
+ String getLast_name()
+ void setLast_name(String)
+ Address getAddress()
+ void setAddress(Address)
+ String getPhone_num()
+ void setPhone_num(String)
+ String getBirth_date()
+ void setBirth_date(String)
+ String getEmail()
+ void setEmail(String)
+ ArrayList<String> getMassages_res()
}
class VolunteerLogIn {
- Button volunteerLoginBtn
- Button volunteerCreateUser
- Button volunteerLoginBack
- TextView volunteerEmailEditText
- TextView volunteerPasswordEditText
- FirebaseAuth mAuth
# void onCreate(Bundle)
- void loginUser(String,String)
}
interface Association_user {
+ String getPhone_num()
+ void setPhone_num(String)
+ Address getAddress()
+ void setAddress(Address)
+ String getName()
+ void setName(String)
+ String getEmail()
+ void setEmail(String)
+ String getAbout()
+ void setAbout(String)
+ ArrayList<String> getPosts()
+ ArrayList<String> getMassages_req()
}
class FeedPostsAssociation {
- RecyclerView postsRecycle
- DatabaseReference mRootRef
~ String association_user_id
~ ArrayList<String> cur_posts
~ ArrayList<Pair<Assoc_post,String>> posts
~ int num_of_posts
# void onCreate(Bundle)
}
class EditPost {
- Button update
- EditText NameInsert
- EditText PhoneNumberInsert
- EditText addresscityinsert
- EditText addressstreetinsert
- EditText addressnuminsert
- EditText postnumofvol
- EditText postdescreption
- Spinner spintype
- DatabaseReference mDatabase
~ String assoc_id
~ String post_id
~ Assoc_post post_n
# void onCreate(Bundle)
- void update_post(String,String,String,String,String,String)
}
class EditAssociation {
- Button add_changes
- EditText NameInsert
- EditText PhoneNumberInsert
- EditText addresscityinsert
- EditText addressstreetinsert
- EditText addressnuminsert
- EditText assocInfo
- DatabaseReference mDatabase
~ String assoc_id
~ Assoc_user assoc_user
# void onCreate(Bundle)
- void update_data(String,String,String,int,String,String)
}
class InboxResponses {
- RecyclerView recycleResponses
- DatabaseReference mRootRef
~ String response_id
~ ArrayList<Pair<Response,String>> responses
# void onCreate(Bundle)
}
class AssociationPage {
- Button edit
- Button addPost
- Button logOut
- Button see_posts
- Button inboxRequests
- TextView NameInsert
- TextView PhoneNumberInsert
- TextView EmailInsert
~ String assoc_id
- DatabaseReference mDatabase
# void onCreate(Bundle)
}
class Assoc_post {
+ String userId
- String name
- Address location
- int num_of_participants
- String type
- String phone_number
- String description
+ <<Create>> Assoc_post(String,Address,int,String,String,String,String)
+ <<Create>> Assoc_post()
+ String getName()
+ void setName(String)
+ Address getLocation()
+ void setLocation(Address)
+ int getNum_of_participants()
+ void setNum_of_participants(int)
+ String getType()
+ void setType(String)
+ String getDescription()
+ void setDescription(String)
+ String getPhone_number()
+ void setPhone_number(String)
}
class AdapterPostVol {
~ Context context
~ String vol_user_id
~ ArrayList<Pair<Assoc_post,String>> listPosts
+ <<Create>> AdapterPostVol(Context,String)
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
+ void setPosts(ArrayList<Pair<Assoc_post,String>>)
}
class AdapterPostVol.ViewHolder {
- TextView txtNameAssociation
- Button btnSeeMoreDetails
- CardView parent
+ <<Create>> ViewHolder(View)
}
class FeedPostGuest {
- RecyclerView postsRecycle
- DatabaseReference mRootRef
~ ArrayList<Pair<Assoc_post,String>> posts
# void onCreate(Bundle)
}
class MainActivity {
- Button volunteerLoginBtn
- Button associationLoginBtn
- Button guestLoginBtn
- Button btnMessage
# void onCreate(Bundle)
}
class AdapterResponse {
~ Context context
~ String ass_user_id
~ ArrayList<Pair<Response,String>> listResponse
+ <<Create>> AdapterResponse(Context,String)
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
+ void setResponses(ArrayList<Pair<Response,String>>)
}
class AdapterResponse.ViewHolder {
- TextView txtNameResponse
- Button btnSeeMoreDetails
- CardView parent
+ <<Create>> ViewHolder(View)
}
class AdapterPostAssociation {
~ Context context
~ String association_user_id
~ ArrayList<Pair<Assoc_post,String>> listPosts
+ <<Create>> AdapterPostAssociation(Context,String)
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
+ void setPosts(ArrayList<Pair<Assoc_post,String>>)
}
class AdapterPostAssociation.ViewHolder {
- TextView txtNameAssociation
- Button btnSeeMoreDetails
- CardView parent
+ <<Create>> ViewHolder(View)
}
class AssociationSignUp {
- EditText inputName
- EditText inputCity
- EditText inputStreet
- EditText inputHouseNumber
- EditText inputPhone
- EditText inputAbout
- EditText inputMail
- EditText inputPassword1
- EditText inputPassword2
- Button register
- Button logInAssociation
- FirebaseAuth mAuth
- DatabaseReference mRootRef
# void onCreate(Bundle)
- void registerUser(String,String,String,String,String,String,String,String)
}
class Response {
- String vol_user_id
- String association_user_id
- String post_id
- Status status
+ <<Create>> Response(String,String,String,Status)
+ String getVol_user_id()
+ void setVol_user_id(String)
+ String getAssociation_user_id()
+ void setAssociation_user_id(String)
+ String getPost_id()
+ void setPost_id(String)
+ Status getStatus()
+ void setStatus(Status)
}
interface Request {
+ String getVol_user_id()
+ void setVol_user_id(String)
+ String getPost_id()
+ void setPost_id(String)
+ String getContent()
+ void setContent(String)
+ int getNum_of_vol()
+ void setNum_of_vol(int)
+ Status getStatus()
+ void setStatus(Status)
}
class RequestAssociation {
- Button SendRequest
- Button Back
- TextView volName
- TextView volEmail
- EditText content
- EditText numParticipant
- DatabaseReference mDatabase
~ String vol_user_id
~ String post_id
~ String Assoc_id
~ Request cur_req
# void onCreate(Bundle)
- void send_request(String,String)
}
class Add_post {
- EditText inputName
- EditText inputCity
- EditText inputStreet
- EditText inputNum
- EditText inputPhone
- EditText inputDescription
- EditText inputNumOfParticipants
- Button addPost
- Button backToAssoc
- Spinner spintype
- DatabaseReference mDatabase
~ String assoc_id
# void onCreate(Bundle)
+ void add_post_info(String,String,String,String,String,String,String,String)
}
class DetailsRequest {
- TextView PostName
- Button back
- DatabaseReference mRootRef
~ String request_id
~ String assoc_id
~ String post_name
~ String vol_user_name
~ String vol_user_email
~ Request_vol cur_req
# void onCreate(Bundle)
+ void update_information()
}
class FeedPostsVol {
- RecyclerView postsRecycle
- DatabaseReference mRootRef
~ String vol_user_id
~ ArrayList<Pair<Assoc_post,String>> posts
# void onCreate(Bundle)
}
class postShape {
- Button btnSeeDetails
# void onCreate(Bundle)
}
class VolunteerUserSignUp {
- EditText inputFirstName
- EditText inputLastName
- EditText inputCity
- EditText inputStreet
- EditText inputHouseNumber
- EditText inputBirthday
- EditText inputPassword1
- EditText inputPassword2
- EditText inputMail
- Button register
- Button logInVolunteer
- TextView mDisplayDate
- DatePickerDialog.OnDateSetListener mDateSetListener
- FirebaseAuth mAuth
- DatabaseReference mRootRef
~ String BirthDay
# void onCreate(Bundle)
- void registerUser(String,String,String,String,String,String,String,String)
}
class Request_vol {
- String vol_user_id
- String post_id
- String content
- int num_of_vol
- Status status
+ <<Create>> Request_vol(String,String,String,int,Status)
+ <<Create>> Request_vol()
+ Status getStatus()
+ void setStatus(Status)
+ int getNum_of_vol()
+ void setNum_of_vol(int)
+ String getVol_user_id()
+ String getContent()
+ void setContent(String)
+ void setVol_user_id(String)
+ String getPost_id()
+ void setPost_id(String)
}
interface Response_Interface {
+ String getVol_user_id()
+ void setVol_user_id(String)
+ void setAssociation_user_id(String)
+ String getAssociation_user_id()
+ Status getStatus()
+ void setStatus(Status)
+ String getPost_id()
+ void setPost_id(String)
}
class DetailsPostAssociation {
- TextView PostName
- Button back
- ImageView post_pic
- DatabaseReference mDatabase
- StorageReference mystorge
~ String association_user_id
~ String post_id
# void onCreate(Bundle)
}
class GuestUser {
- Button back
- Button vol_events
# void onCreate(Bundle)
}
class Address {
~ String city
~ String street
~ int number
+ <<Create>> Address(String,String,int)
+ <<Create>> Address()
+ String getStreet()
+ void setStreet(String)
+ int getNumber()
+ void setNumber(int)
+ String getCity()
+ void setCity(String)
}
class AdapterReqAssociation {
~ Context context
~ String assoc_id
~ ArrayList<Pair<Request_vol,String>> listRequests
+ <<Create>> AdapterReqAssociation(Context,String)
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
+ void setListRequests(ArrayList<Pair<Request_vol,String>>)
}
class AdapterReqAssociation.ViewHolder {
- TextView MailVolRequestToAss
- Button btnSeeDetailsRequestToAss
- CardView parentRequestToAss
- DatabaseReference mDatabase
+ <<Create>> ViewHolder(View)
}
class AssociationLogIn {
- Button associationLoginBtn
- Button associationCreateUser
- Button associationLoginBack
- TextView associationEmailEditText
- TextView associationPasswordEditText
- FirebaseAuth mAuth
# void onCreate(Bundle)
- void loginUser(String,String)
}
class InboxAssociation {
- RecyclerView recycleRequests
- DatabaseReference mRootRef
~ String assoc_id
~ ArrayList<String> cur_requests
~ ArrayList<Pair<Request_vol,String>> requests
~ int num_of_requests
# void onCreate(Bundle)
}
interface Association_post {
+ String getName()
+ void setName(String)
+ Address getLocation()
+ void setLocation(Address)
+ int getNum_of_participants()
+ void setNum_of_participants(int)
+ String getType()
+ void setType(String)
+ String getPhone_number()
+ void setPhone_number(String)
+ String getDescription()
+ void setDescription(String)
}
class picture_edit_post {
- Button btnSelect
- ImageView imageView
- Uri filePath
- int PICK_IMAGE_REQUEST
~ FirebaseStorage storage
~ StorageReference storageReference
~ String assoc_id
~ String post_id
# void onCreate(Bundle)
- void SelectImage()
# void onActivityResult(int,int,Intent)
- void uploadImage()
}
class AdapterPostGuest {
~ Context context
~ ArrayList<Pair<Assoc_post,String>> listPosts
+ <<Create>> AdapterPostGuest(Context)
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
+ void setPosts(ArrayList<Pair<Assoc_post,String>>)
}
class AdapterPostGuest.ViewHolder {
- TextView txtNameAssociation
- Button btnSeeMoreDetails
- CardView parent
+ <<Create>> ViewHolder(View)
}
class DetailsPostVol {
- TextView PostName
- Button back
- ImageView post_pic
- DatabaseReference mDatabase
- StorageReference mystorge
~ String vol_user_id
~ String post_id
~ String assoc_id
# void onCreate(Bundle)
}
class requestShape {
# void onCreate(Bundle)
}


AppCompatActivity <|-- picture_edit_vol
Association_user <|.. Assoc_user
AppCompatActivity <|-- EditVolunteer
AppCompatActivity <|-- VolunteerPage
Volunteer_user <|.. Vol_user
AppCompatActivity <|-- responseShape
AppCompatActivity <|-- DetailsPostGuest
AppCompatActivity <|-- VolunteerLogIn
AppCompatActivity <|-- FeedPostsAssociation
AppCompatActivity <|-- EditPost
AppCompatActivity <|-- EditAssociation
AppCompatActivity <|-- InboxResponses
AppCompatActivity <|-- AssociationPage
Association_post <|.. Assoc_post
Adapter <|-- AdapterPostVol
AdapterPostVol +.. AdapterPostVol.ViewHolder
ViewHolder <|-- AdapterPostVol.ViewHolder
AppCompatActivity <|-- FeedPostGuest
AppCompatActivity <|-- MainActivity
Adapter <|-- AdapterResponse
AdapterResponse +.. AdapterResponse.ViewHolder
ViewHolder <|-- AdapterResponse.ViewHolder
Adapter <|-- AdapterPostAssociation
AdapterPostAssociation +.. AdapterPostAssociation.ViewHolder
ViewHolder <|-- AdapterPostAssociation.ViewHolder
AppCompatActivity <|-- AssociationSignUp
Response_Interface <|.. Response
AppCompatActivity <|-- RequestAssociation
AppCompatActivity <|-- Add_post
AppCompatActivity <|-- DetailsRequest
AppCompatActivity <|-- FeedPostsVol
AppCompatActivity <|-- postShape
AppCompatActivity <|-- VolunteerUserSignUp
Request <|.. Request_vol
AppCompatActivity <|-- DetailsPostAssociation
AppCompatActivity <|-- GuestUser
Adapter <|-- AdapterReqAssociation
AdapterReqAssociation +.. AdapterReqAssociation.ViewHolder
ViewHolder <|-- AdapterReqAssociation.ViewHolder
AppCompatActivity <|-- AssociationLogIn
AppCompatActivity <|-- InboxAssociation
AppCompatActivity <|-- picture_edit_post
Adapter <|-- AdapterPostGuest
AdapterPostGuest +.. AdapterPostGuest.ViewHolder
ViewHolder <|-- AdapterPostGuest.ViewHolder
AppCompatActivity <|-- DetailsPostVol
AppCompatActivity <|-- requestShape
@enduml